export const InviteFormInputs = [
  {
    name: "schoolName",
    type: "text",
    label: "School Name",
    placeholder: "Enter school name",
    required: true,
  },
  {
    name: "adminName",
    type: "text",
    label: "Admin Contact Name",
    placeholder: "Enter administrator's name",
    required: true,
  },
  {
    name: "contactEmail",
    type: "email",
    label: "Contact Email",
    placeholder: "Enter contact email",
    required: true,
  },
  {
    name: "contactPhone",
    type: "tel",
    label: "Phone Number",
    placeholder: "Enter contact phone number",
    required: true,
  },
  {
    name: "country",
    type: "select",
    label: "Country",
    placeholder: "Select country",
    required: true,
    options: ["Pakistan", "Turkey", "Malawi", "England", "USA", "India"],
  },
  {
    name: "schoolID",
    type: "text",
    label: "School ID",
    placeholder: "Enter school ID or registration number",
    required: true,
  },
  {
    name: "curriculum",
    type: "select",
    label: "Curriculum Followed",
    placeholder: "Select curriculum",
    required: true,
    options: [
      "IGCSE",
      "A-Levels",
      "National Board",
      "Private Curriculam",
      "Madrassa",
      "Selectives",
    ],
  },
  {
    name: "branch",
    type: "text",
    label: "Branch Name",
    placeholder: "Enter branch name if applicable",
    required: true,
  },
  {
    name: "city",
    type: "text",
    label: "City",
    placeholder: "Enter city",
    required: true,
  },
];
